---
# tasks file for make-proj-env
- name: Create Directory for outcomes
  become: yes
  file:
    path: /opt/{{ INPUT}}_{{ EID[19:24] }}
    state: directory
    mode: '777'

- name: Create Directories for logs,chunks etc
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: '777'
  with_items:
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/logs
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/input
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/output
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/video_out
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/temp_dir
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/temp
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/archives
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/backup

- name: Create log files
  become: yes
  file:
    path: "{{ item }}"
    state: touch
    mode: '777'
  with_items:
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/logs/{{ INPUT}}_{{ EID[19:24] }}.log
    - /opt/{{ INPUT}}_{{ EID[19:24] }}/output/output.csv