---
- name: deploy vsftpd
  hosts: all
  tasks:
  - name: install vsftpd
    package:
      name: vsfptd
      state: latest
  - name:
    service: name=vsfptd enabled=true
  - name:
    copy:
      content: "welcome to my friendly server\n"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444
