---
- name: deploy and start apache
  hosts: all
  vars:
    apache_package: apache2
    firewall_package: ufw
    web_service: apache2
    firewall_service: ufw
    rule: apache2
  tasks:
    - name: install and update packages
      apt:
        name:
          - "{{ apache_package }}"
          - "{{ firewall_package }}"
        state: latest
    - name: start and enable {{ firewall_package }}
      service:
        name: "{{ firewall_package }}"
        enabled: true
        state: started
    - name: create web content
      copy:
        content: "welcome to ansible managed web service"
        dest: /var/www/html/index.html
    - name: start and enable {{ web_service }}
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started
    - name: open firewall for {{ rule }}
      ufw:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled
- name: verify web browser
  hosts: localhost
  become: false
  tasks:
    - name: test the web server is available
      uri:
        url: http://localhost.com
        status_code: 200
