- name: Clone Source Code from GitHub
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/ramtulluri/video-ai-analyser.git
    dest: /tmp/github
    version: fd_integ
- name: Update System
  become: yes
  command: apt update
- name: Install Components of Python & Python Env
  become: yes
  apt:
    name: "{{ req_pyth_name }}"
    state: present
- name: Creating Directory
  become: yes
  command: mkdir -p /home/python/myproj
- name: Creating Virtual Env with Python
  become: yes
  command: chdir=/home/python/myproj {{ item }}
  with_items:
  - python3.6 -m venv myprojectenv
# - name: Copy Source Code from tmp
#   become: yes
#   command: cp -r /tmp/github/. /home/python/myproj/
- name: Installing flask application dependents
  pip:
    name: "{{ req_flask_pip }}"
    executable: pip
- name: Copy Rest Server file
  become: yes
  copy:
    src: /home/administrator/ansibleproj/{{ item }}
    dest: /home/python/myproj
  with_items:
  - ansibleproj.py
  - wsgi.py
- name: Create Service File
  become: yes
  copy:
    src: /home/administrator/ansibleproj/ansproj.service
    dest: /etc/systemd/system
- name: Daemon Reload
  become: yes
  command: systemctl daemon-reload
- name: Start the Count Service
  become: yes
  systemd:
    state: started
    name: ansproj

