---
- name: System details
  debug: msg="{{ item }}"
  with_items: 
  - "{{ ansible_distribution }}"
  - "{{ ansible_distribution_version }}"
  - "{{ ansible_distribution_major_version }}"

- name: Update System
  apt:
    update-cache: yes
    force_apt_get: yes

- name: Upgrade all apt packages
  apt: 
    upgrade: dist
    force_apt_get: yes

- name: Ensure nginx packages are present
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_packages }}"
  notify: restart-nginx-service
  
- name: Ensure uwsgi package is present
  pip:
    name: uwsgi
    state: present
  notify: restart-nginx-service
  
- name: Ensure latest default.conf is present
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: restart-nginx-service
  
- name: Ensure latest index.html is present
  template:
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
  
- name: Ensure nginx service is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
  
  # smoke test that nginx came up and is serving home page
- name: Ensure proper response from localhost is received
  uri:
    url: http://localhost/
    return_content: yes
  register: response
  until: 'nginx_test_message in response.content'
  retries: 10
  delay: 1