---
- name: Installing webserves on Debian Family
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Installing webserves on RedHat Family
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
