- name: Install apache2 web server
  become: true
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Installing fastcgi
  become: yes
  apt: 
    deb: http://mirrors.kernel.org/ubuntu/pool/multiverse/liba/libapache-mod-fastcgi/libapache2-mod-fastcgi_2.4.7~0910052141-1.2_amd64.deb

- name: Upgrade all packages to the latest version
  become: yes
  apt:
    name: "*"
    state: latest

- name: install system updates for ubuntu systems
  become: yes
  apt: 
    upgrade: dist 
    update_cache: yes
  
- name: Enable apache2 modules
  become: yes
  command: a2enmod rewrite actions alias fastcgi proxy_fcgi

- name: Upload apache2 default configuration
  become: yes
  copy: src=files/000-default.conf dest=/etc/apache2/sites-enabled/

- name: Remove default apache2 index.html file
  become: yes
  ignore_errors: yes
  command: rm /var/www/html/index.html 

- name: Upload default index.php for host 
  become: yes
  copy: src=files/index.php dest=/var/www/html/ mode=0644  

- name: Restart webserver
  become: yes
  service: name=apache2 state=restarted