---

- hosts: all
  become: true
  become_method: sudo
  gather_facts: false
  vars_files:
    - vars/var.yml
  pre_tasks:
  - name: Install pip3
    apt:
      name: "{{ python_pip }}"
      state: present
  - name: Install Cmake
    apt:
      name: "{{ req_cmake_name }}"
      state: present
      update_cache: yes
  - name: Install dependent pip packages
    pip:
      name: "{{ req_pip_pack }}"
      executable: pip3
- hosts: restservers
  vars_files:
    - vars/var.yml
  roles:
    - countcode
  vars_prompt:
    - name: "githubuser"
      prompt: "Enter your github username"
      private: no
    - name: "githubpassword"
      prompt: "Enter your github password"
      private: yes
